sudo: required
language: go

go:
- 1.13.x

script:
- make fmt
- make test
- make dist
- ./ci/hashgen.sh

deploy:
  provider: releases
  api_key:
    secure: cM5++9tbedJaA5hauGZ2U03Ny7dR1L0pzmZJ3MAvAVpo24tjWwMNrTp6DTckvNOhSFmJhQ+RLSocnFSsvYJL5JWDWMt2ZLl5ouac3YO4GfeTLHTZEmKs458PLw1nYd9mZVZb6qhRBnfO2pvO+wmjohXiTx71p/v150QPpFcdEyvi9p0y5Rl+ErEj0uumvijsHWFDKsYCoSXAqOJgGfwPMco8oMmyqSUMWU0EhNZoLAwfB1SrZiirW+MP8aKAWhTZLXsCNAYhLTof+zvmkqxjkthaUZLWM+WnC82bD3b0dXo/HA5UvpEzsAa+fyibOfQ31fkHYOUd/bS1WHtf6SAp6equZ1i4NlXTrxDz+qiT28nlA1+pOe9T8mFfEYm9wrfr52ibvcJSjhKa+xcGdA/4HZbl4lq5MJH938zwMVg2PzkKwj7PAOdzLMT5G13ilw8siZgH4H+0LROZCllVCvxAk8jiRDfvAYUfJPRl0HpgMtGrHmGt9c5OL/6MstRlfckRaZpCRBDoiczJBy6gpemXVF/pzzXpZu2XEVyk4KY2m9BLSq1ovYQAcAd4ZxP8HxUpNex8PClXmWqiIeRCttSTQnCB6WhtLqqNsYa5lLMZFpTR7YJxOy4kVuTRHb8tnVeqCP00P7IwEjr2arVj9Ncz2kVv2oxPdnUwcaURMhqcymA=
  prerelease: false
  overwrite: true
  file: 
  - bin/k3sup
  - bin/k3sup-arm64
  - bin/k3sup-armhf
  - bin/k3sup-darwin
  - bin/k3sup.exe
  - bin/k3sup.sha256
  - bin/k3sup-arm64.sha256
  - bin/k3sup-armhf.sha256
  - bin/k3sup-darwin.sha256
  - bin/k3sup.exe.sha256

  skip_cleanup: true
  on:
    tags: true

env:
- GO111MODULE=on
